packages:
  - apps/*
  - extensions/*
  - packages/*

ignoredBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - baileys
  - electron
  - esbuild
  - msedge-tts
  - onnxruntime-node
  - prisma
  - protobufjs
  - sharp
