"""
setup.py

Interactive setup wizard for Orion.
Walks the user through configuring all required credentials and tests connectivity.

Run with: python scripts/setup.py

Part of Orion - Persistent AI Companion System.
"""

import os
import sys
from pathlib import Path

project_root = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(project_root))

from dotenv import load_dotenv

ENV_PATH = project_root / ".env"


def print_header() -> None:
    """Print the Orion Setup Wizard header."""
    print()
    print("=" * 60)
    print("   ORION SETUP WIZARD")
    print("=" * 60)
    print()


def prompt_input(
    label: str, default: str = "", required: bool = False, hint: str = ""
) -> str:
    """
    Prompt user for input with optional default and hint.

    Args:
        label: The prompt label.
        default: Default value if user presses Enter.
        required: If True, re-prompt until a value is provided.
        hint: Optional hint text shown after the prompt.

    Returns:
        The user input string.
    """
    prompt_text = f"  {label}"
    if default:
        prompt_text += f" [{default}]"
    prompt_text += ": "

    if hint:
        print(f"    {hint}")

    while True:
        try:
            value = input(prompt_text).strip()
        except (EOFError, KeyboardInterrupt):
            print("\nSetup cancelled.")
            sys.exit(0)

        if value:
            return value
        if default:
            return default
        if not required:
            return ""
        print("    This value is required. Please enter a value.")


def prompt_yes_no(label: str, default: bool = False) -> bool:
    """
    Prompt user for yes/no confirmation.

    Args:
        label: The prompt label.
        default: Default value if user presses Enter.

    Returns:
        True for yes, False for no.
    """
    default_str = "Y/n" if default else "y/N"
    prompt_text = f"  {label} [{default_str}]: "

    try:
        value = input(prompt_text).strip().lower()
    except (EOFError, KeyboardInterrupt):
        print("\nSetup cancelled.")
        sys.exit(0)

    if not value:
        return default
    return value in ("y", "yes", "true", "1")


def load_existing_env() -> dict:
    """
    Load existing .env values if the file exists.

    Returns:
        Dict of existing environment variables.
    """
    if not ENV_PATH.exists():
        return {}

    existing = {}
    with open(ENV_PATH, "r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            if "=" in line:
                key, _, value = line.partition("=")
                existing[key.strip()] = value.strip()

    return existing


def write_env(values: dict, existing: dict) -> None:
    """
    Write values to .env file, preserving existing values unless overwritten.

    Args:
        values: New values to write.
        existing: Existing values from .env file.
    """
    merged = existing.copy()

    for key, value in values.items():
        if value:
            merged[key] = value

    lines = [
        "# ============================================",
        "# Orion - Environment Variables",
        "# ============================================",
        "# Generated by setup.py",
        "# ============================================",
        "",
    ]

    sections = {
        "Anthropic - API Key": ["ANTHROPIC_API_KEY"],
        "OpenAI - Optional": ["OPENAI_API_KEY"],
        "Google Gemini - Optional": ["GEMINI_API_KEY"],
        "Telegram - Required for delivery": ["TELEGRAM_BOT_TOKEN", "TELEGRAM_CHAT_ID"],
        "Database": ["DATABASE_URL"],
        "User Config": ["DEFAULT_USER_ID"],
        "Ollama - Local Free": ["OLLAMA_BASE_URL"],
        "Voice": ["WHISPER_MODEL", "TTS_ENGINE"],
        "Vision": ["VISION_ENGINE", "VISION_MODE"],
        "Config": ["DEFAULT_ENGINE", "LOG_LEVEL", "PERMISSIONS_CONFIG"],
    }

    for section_title, keys in sections.items():
        lines.append(f"# {section_title}")
        for key in keys:
            value = merged.get(key, "")
            lines.append(f"{key}={value}")
        lines.append("")

    with open(ENV_PATH, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))

    print(f"\n  Configuration saved to: {ENV_PATH}")


def test_claude(api_key: str) -> tuple[bool, str]:
    """
    Test Claude API connectivity.

    Args:
        api_key: Anthropic API key.

    Returns:
        Tuple of (success, message).
    """
    try:
        import anthropic

        client = anthropic.Anthropic(api_key=api_key)
        client.models.list()
        return True, "OK"
    except ImportError:
        return False, "FAILED - anthropic package not installed"
    except Exception as exc:
        return False, f"FAILED - {exc}"


def test_openai(api_key: str) -> tuple[bool, str]:
    """
    Test OpenAI API connectivity.

    Args:
        api_key: OpenAI API key.

    Returns:
        Tuple of (success, message).
    """
    try:
        import openai

        client = openai.OpenAI(api_key=api_key)
        client.models.list()
        return True, "OK"
    except ImportError:
        return False, "FAILED - openai package not installed"
    except Exception as exc:
        return False, f"FAILED - {exc}"


def test_gemini(api_key: str) -> tuple[bool, str]:
    """
    Test Gemini API connectivity.

    Args:
        api_key: Google Gemini API key.

    Returns:
        Tuple of (success, message).
    """
    try:
        import google.generativeai as genai

        genai.configure(api_key=api_key)
        list(genai.list_models())
        return True, "OK"
    except ImportError:
        return False, "FAILED - google-generativeai package not installed"
    except Exception as exc:
        return False, f"FAILED - {exc}"


def test_telegram(bot_token: str) -> tuple[bool, str]:
    """
    Test Telegram Bot API connectivity.

    Args:
        bot_token: Telegram bot token.

    Returns:
        Tuple of (success, message).
    """
    try:
        import requests

        url = f"https://api.telegram.org/bot{bot_token}/getMe"
        response = requests.get(url, timeout=10)
        data = response.json()

        if data.get("ok"):
            bot_info = data.get("result", {})
            username = bot_info.get("username", "unknown")
            return True, f"OK - @{username}"
        return False, f"FAILED - {data.get('description', 'unknown error')}"
    except ImportError:
        return False, "FAILED - requests package not installed"
    except Exception as exc:
        return False, f"FAILED - {exc}"


def run_connectivity_tests(values: dict) -> None:
    """
    Run connectivity tests for all provided credentials.

    Args:
        values: Dict of configured values.
    """
    print("\n" + "-" * 60)
    print("  CONNECTIVITY TESTS")
    print("-" * 60)

    results = {
        "claude": {"tested": False, "success": False, "message": ""},
        "openai": {"tested": False, "success": False, "message": ""},
        "gemini": {"tested": False, "success": False, "message": ""},
        "telegram": {"tested": False, "success": False, "message": ""},
    }

    if values.get("ANTHROPIC_API_KEY"):
        print("\n  Testing Claude (Anthropic)...")
        success, message = test_claude(values["ANTHROPIC_API_KEY"])
        results["claude"] = {"tested": True, "success": success, "message": message}
        status = "[OK]" if success else "[FAILED]"
        print(f"    {status} {message}")

    if values.get("OPENAI_API_KEY"):
        print("\n  Testing OpenAI...")
        success, message = test_openai(values["OPENAI_API_KEY"])
        results["openai"] = {"tested": True, "success": success, "message": message}
        status = "[OK]" if success else "[FAILED]"
        print(f"    {status} {message}")

    if values.get("GEMINI_API_KEY"):
        print("\n  Testing Gemini...")
        success, message = test_gemini(values["GEMINI_API_KEY"])
        results["gemini"] = {"tested": True, "success": success, "message": message}
        status = "[OK]" if success else "[FAILED]"
        print(f"    {status} {message}")

    if values.get("TELEGRAM_BOT_TOKEN"):
        print("\n  Testing Telegram...")
        success, message = test_telegram(values["TELEGRAM_BOT_TOKEN"])
        results["telegram"] = {"tested": True, "success": success, "message": message}
        status = "[OK]" if success else "[FAILED]"
        print(f"    {status} {message}")


def print_summary(values: dict) -> None:
    """
    Print configuration summary.

    Args:
        values: Dict of configured values.
    """
    print("\n" + "=" * 60)
    print("   CONFIGURATION SUMMARY")
    print("=" * 60)

    services = {
        "Claude": values.get("ANTHROPIC_API_KEY", ""),
        "OpenAI": values.get("OPENAI_API_KEY", ""),
        "Gemini": values.get("GEMINI_API_KEY", ""),
        "Telegram": values.get("TELEGRAM_BOT_TOKEN", ""),
    }

    print("\n  Services configured:")
    for service, key in services.items():
        status = "ready" if key else "skipped"
        print(f"    {service:12} [{status}]")

    db_url = values.get("DATABASE_URL", "sqlite:///orion.db")
    print(f"\n  Database: {db_url}")
    print(f"  Default User ID: {values.get('DEFAULT_USER_ID', 'owner')}")

    print("\n" + "-" * 60)
    print("  NEXT STEPS")
    print("-" * 60)
    print("\n  1. Run: python scripts/first_run.py")
    print("     (Tests database, engines, and daemon)")
    print("\n  2. Run: python main.py")
    print("     (Start Orion chat loop)")
    print("\n" + "=" * 60)


def main() -> None:
    """
    Run the interactive setup wizard.

    Steps:
        1. Print header
        2. Collect credentials from user
        3. Write to .env file
        4. Run connectivity tests
        5. Print summary
    """
    print_header()

    existing = load_existing_env()

    if existing:
        print("  Found existing .env file. Values will be preserved unless changed.\n")

    print("  Required credentials:")
    print("-" * 60)

    values = {}

    print("\n  --- Anthropic Claude (Required) ---")
    print("  Claude is the primary reasoning engine for Orion.")
    existing_key = existing.get("ANTHROPIC_API_KEY", "")
    if existing_key:
        print(f"  Existing key found: {existing_key[:8]}...{existing_key[-4:]}")
        if not prompt_yes_no("Change it?", default=False):
            values["ANTHROPIC_API_KEY"] = existing_key
        else:
            values["ANTHROPIC_API_KEY"] = prompt_input(
                "ANTHROPIC_API_KEY", required=True
            )
    else:
        values["ANTHROPIC_API_KEY"] = prompt_input("ANTHROPIC_API_KEY", required=True)

    print("\n  --- Telegram (Required for delivery) ---")
    print("  Telegram is used for proactive messages and confirmations.")

    existing_token = existing.get("TELEGRAM_BOT_TOKEN", "")
    if existing_token:
        print(f"  Existing token found: {existing_token[:8]}...{existing_token[-4:]}")
        if not prompt_yes_no("Change it?", default=False):
            values["TELEGRAM_BOT_TOKEN"] = existing_token
        else:
            values["TELEGRAM_BOT_TOKEN"] = prompt_input(
                "TELEGRAM_BOT_TOKEN", required=True
            )
    else:
        values["TELEGRAM_BOT_TOKEN"] = prompt_input("TELEGRAM_BOT_TOKEN", required=True)

    print("\n  How to get your TELEGRAM_CHAT_ID:")
    print("    1. Open Telegram and search for @userinfobot")
    print("    2. Start a conversation with it")
    print("    3. It will reply with your chat ID")

    existing_chat_id = existing.get("TELEGRAM_CHAT_ID", "")
    if existing_chat_id:
        print(f"  Existing chat ID found: {existing_chat_id}")
        if not prompt_yes_no("Change it?", default=False):
            values["TELEGRAM_CHAT_ID"] = existing_chat_id
        else:
            values["TELEGRAM_CHAT_ID"] = prompt_input("TELEGRAM_CHAT_ID", required=True)
    else:
        values["TELEGRAM_CHAT_ID"] = prompt_input("TELEGRAM_CHAT_ID", required=True)

    print("\n  --- Optional API Keys ---")
    print("  Press Enter to skip any of these.\n")

    existing_openai = existing.get("OPENAI_API_KEY", "")
    if existing_openai:
        print(f"  OPENAI_API_KEY: {existing_openai[:8]}...{existing_openai[-4:]}")
        if prompt_yes_no("Change it?", default=False):
            values["OPENAI_API_KEY"] = prompt_input("OPENAI_API_KEY")
        else:
            values["OPENAI_API_KEY"] = existing_openai
    else:
        values["OPENAI_API_KEY"] = prompt_input("OPENAI_API_KEY (optional)")

    existing_gemini = existing.get("GEMINI_API_KEY", "")
    if existing_gemini:
        print(f"  GEMINI_API_KEY: {existing_gemini[:8]}...{existing_gemini[-4:]}")
        if prompt_yes_no("Change it?", default=False):
            values["GEMINI_API_KEY"] = prompt_input("GEMINI_API_KEY")
        else:
            values["GEMINI_API_KEY"] = existing_gemini
    else:
        values["GEMINI_API_KEY"] = prompt_input("GEMINI_API_KEY (optional)")

    print("\n  --- Database Configuration ---")

    existing_db = existing.get("DATABASE_URL", "")
    default_db = existing_db or "sqlite:///orion.db"

    print("  SQLite (default) - Quick local start, no setup required.")
    print("  PostgreSQL - Recommended for production.")
    print()

    if existing_db:
        print(f"  Existing DATABASE_URL: {existing_db}")
        if not prompt_yes_no("Change it?", default=False):
            values["DATABASE_URL"] = existing_db
        else:
            values["DATABASE_URL"] = prompt_input("DATABASE_URL", default=default_db)
    else:
        values["DATABASE_URL"] = prompt_input("DATABASE_URL", default=default_db)

    print("\n  --- User Configuration ---")

    existing_user = existing.get("DEFAULT_USER_ID", "owner")
    values["DEFAULT_USER_ID"] = prompt_input("DEFAULT_USER_ID", default=existing_user)

    values["DEFAULT_ENGINE"] = "claude"
    values["OLLAMA_BASE_URL"] = existing.get(
        "OLLAMA_BASE_URL", "http://localhost:11434"
    )
    values["WHISPER_MODEL"] = existing.get("WHISPER_MODEL", "base")
    values["TTS_ENGINE"] = existing.get("TTS_ENGINE", "coqui")
    values["VISION_ENGINE"] = existing.get("VISION_ENGINE", "gemini")
    values["VISION_MODE"] = existing.get("VISION_MODE", "passive")
    values["LOG_LEVEL"] = existing.get("LOG_LEVEL", "INFO")
    values["PERMISSIONS_CONFIG"] = existing.get(
        "PERMISSIONS_CONFIG", "permissions/permissions.yaml"
    )

    write_env(values, existing)

    run_connectivity_tests(values)

    print_summary(values)


if __name__ == "__main__":
    main()
